#
# Makefile for the linux kernel.
#

obj-y += iomux_config.o
obj-y += audmux_iomux_config.o
obj-y += eim_iomux_config.o
obj-y += enet_iomux_config.o
obj-y += gpio4_iomux_config.o
obj-y += gpio6_iomux_config.o
obj-y += gpio7_iomux_config.o
obj-y += hdmi_iomux_config.o
obj-y += i2c1_iomux_config.o
obj-y += i2c3_iomux_config.o
obj-y += mmdc_iomux_config.o
obj-y += sjc_iomux_config.o
obj-y += uart1_iomux_config.o
obj-y += usb_iomux_config.o
obj-y += usdhc3_iomux_config.o
obj-y += usdhc4_iomux_config.o

